# Generated by Django 4.0.4 on 2022-04-17 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisweb', '0002_address_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_prefix', models.CharField(max_length=10)),
                ('teacher_firstname', models.CharField(max_length=255)),
                ('teacher_lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('teacher_img', models.CharField(max_length=255)),
                ('id_card', models.IntegerField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('role', models.CharField(max_length=255)),
                ('certificate', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('teacher_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$'), django.core.validators.MinLengthValidator(13)])),
                ('teacher_email', models.EmailField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.log_in')),
            ],
        ),
    ]
