# Generated by Django 4.0.4 on 2022-04-17 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisweb', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Company',
            fields=[
                ('address_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$'), django.core.validators.MinLengthValidator(13)])),
                ('company_name', models.CharField(max_length=255)),
                ('soi', models.CharField(max_length=255)),
                ('road', models.CharField(max_length=255)),
                ('subdistrict', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('postcode', models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_firstname', models.CharField(max_length=255)),
                ('staff_lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('staff_img', models.CharField(max_length=1)),
                ('id_card', models.IntegerField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('staff_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$'), django.core.validators.MinLengthValidator(13)])),
                ('staff_email', models.EmailField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.log_in')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_firstname', models.CharField(max_length=255)),
                ('student_lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('student_img', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('id_card', models.IntegerField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('campus', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('study_year', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('gpax', models.DecimalField(decimal_places=2, max_digits=3)),
                ('student_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$'), django.core.validators.MinLengthValidator(13)])),
                ('student_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Train_Contact',
            fields=[
                ('train_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_number', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=255)),
                ('soi', models.CharField(max_length=255)),
                ('road', models.CharField(max_length=255)),
                ('subdistrict', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postcode', models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('institute_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$'), django.core.validators.MinLengthValidator(13)])),
                ('institute_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('visualization_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=255)),
                ('propotion_of_company', models.CharField(max_length=255)),
                ('total_account_company', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='address_student',
            name='postcode',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.CreateModel(
            name='Upload_Document',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('internship_application_form', models.CharField(max_length=255)),
                ('job_application', models.CharField(max_length=255)),
                ('establishment_proposal', models.CharField(max_length=255)),
                ('transcript', models.CharField(max_length=255)),
                ('student_certificate', models.CharField(max_length=255)),
                ('copy_ID_card', models.CharField(max_length=255)),
                ('courtesy_letter', models.CharField(max_length=255)),
                ('acceptance_form', models.CharField(max_length=255)),
                ('letter_of_surrender', models.CharField(max_length=255)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.staff')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='address_stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.address_student'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.log_in'),
        ),
        migrations.CreateModel(
            name='Internship_Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('internship_policy', models.CharField(max_length=255)),
                ('steps_for_internships', models.CharField(max_length=255)),
                ('internship_schedule', models.CharField(max_length=255)),
                ('internship_application_form', models.CharField(max_length=255)),
                ('establishment_proposal', models.CharField(max_length=255)),
                ('job_application', models.CharField(max_length=255)),
                ('internship_documents', models.CharField(max_length=255)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Coop_Train',
            fields=[
                ('coop_train_id', models.AutoField(primary_key=True, serialize=False)),
                ('intstitute_name', models.CharField(max_length=255)),
                ('curriculum', models.CharField(max_length=255)),
                ('datetime_event', models.CharField(max_length=255)),
                ('start_apply', models.DateTimeField()),
                ('deadline_apply', models.DateTimeField()),
                ('amount', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('cost', models.IntegerField(max_length=6)),
                ('link_detail', models.CharField(max_length=255)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.staff')),
                ('train_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.train_contact')),
            ],
        ),
        migrations.CreateModel(
            name='Coop_Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('company_career_link', models.CharField(max_length=255)),
                ('address_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.address_company')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_apply', models.DateTimeField()),
                ('deadline_apply', models.DateTimeField()),
                ('internship_period', models.CharField(max_length=1)),
                ('amount', models.IntegerField(max_length=4)),
                ('allowance', models.IntegerField(max_length=4)),
                ('link_register', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.coop_company')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('agenda_id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.CharField(max_length=255)),
                ('agenda_link', models.CharField(max_length=255)),
                ('coop_train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisweb.coop_train')),
            ],
        ),
    ]
